name: notes_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  adaptive_breakpoints: ^0.1.1
  animations: ^2.0.2

  bitsdojo_window: ^0.1.1+1

  cupertino_icons: ^1.0.4

  file_picker: ^4.3.3
  flex_color_scheme: ^5.0.1
  flutter_markdown: ^0.6.9
  flutter_phoenix: ^1.0.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_widget_from_html: ^0.8.0

  iconsax: ^0.0.8
  intl: ^0.17.0

  line_icons: ^2.0.1
  local_auth: ^2.1.0

  nextcloud: ^3.0.2

  package_info_plus: ^1.3.0
  path_provider: ^2.0.9

  share_plus: ^4.0.4
  shared_preferences: ^2.0.13
  side_navigation: ^1.0.2
  sqflite: ^2.0.2

  uuid: ^3.0.5
  url_launcher: ^6.0.20
  universal_platform: ^1.0.0+1

  yaru_icons: ^0.2.1

  code_text_field: ^1.0.2
  highlight: ^0.7.0
  highlight_text: ^1.4.1
  flutter_highlight: ^0.7.0
  flutter_riverpod: ^2.3.6
  scribble: ^0.9.1
  flutter_signature_pad: ^3.0.0
  syncfusion_flutter_signaturepad: ^22.1.39

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/n_o_t_e_s.png"
  image_path_ios: "images/n_o_t_e_s.png"
  adaptive_icon_foreground: "images/n o t e s.png"
  # adaptive_icon_foreground: "images/n_o_t_e_s_foreground.png"
  adaptive_icon_background: "#45B4D2"

flutter:
  uses-material-design: true

  assets:
    - images/bnotes.png
    - images/bnotes-transparent.png
    - images/google.png
    - images/n_o_t_e_s.png

  fonts:
    - family: Raleway
      fonts:
        - asset: res/Raleway-Regular.ttf
        - asset: res/Raleway-Light.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
